Add API 'fluid.requird_version(min_version, max_version=None)' to check if the installed PaddlePaddle version is satisfied, test=develop (#20263)
添加API：fluid.version_required(min_version, max_version=None)，用于检查已安装的PaddlePaddle版本是否符合要求
无返回值，如果已安装的版本不在区间[min_version, max_version]，则抛出异常。
例：安装的版本为1.6.0，调用：fluid.require_version('1.5.0', '1.5.1')，则抛出异常：
Exception: VersionError: PaddlePaddle version in [1.5.0, 1.5.1] required, but 1.6.0 installed.