Fix build race condition
operator.cc depends on data_feed.pb.h,
so it should have data_feed_proto in its dependecies

Fixes following error:
In file included from /home/tab/dev/external/paddlepaddle/Paddle/paddle/fluid/framework/data_set.h:25,
                 from /home/tab/dev/external/paddlepaddle/Paddle/paddle/fluid/framework/executor.h:22,
                 from /home/tab/dev/external/paddlepaddle/Paddle/paddle/fluid/framework/operator.cc:24:
/home/tab/dev/external/paddlepaddle/Paddle/paddle/fluid/framework/data_feed.h:35:10: fatal error: paddle/fluid/framework/data_feed.pb.h: No such file or directory
 #include "paddle/fluid/framework/data_feed.pb.h"

test=develop